### ISSUE TITLE
resolve security advisory

### ISSUE THREAD

**Issue by martinfrances107** [theta-vn/theta-chart#1]
I love this project but - When I run cargo audit 

I get this warning 

```
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (64 crate dependencies)
Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.26
    └── theta-chart 0.0.5

error: 1 vulnerability found!
```

I have just filed an issue with "time" crate requesting than an security warning already  fixed in the main branch be published to crates.io

[downstream security wasning ](https://github.com/chronotope/chrono/issues/1223)

The fix here when that is complete will be simple.

**Comment by LangPham** [comment]
Temporarily update to version 0.0.6 while waiting for chrono to fix.
- I disbable default-features of chrono to fix
